package com.kotlinapp.gebeya.model

class Server {
    companion object {
        /*var host: String = "newwgenn.com" // Your website address*/
        var host: String = "newwgenn.com" // Your ip address
        var userInfo = "https://" + host + "/user/userInfo.php"
        var login = "https://" + host + "/user/login.php"
        var fbUserInfo = "https://" + host + "/user/fbUserInfo.php"
        var googleUserInfo = "https://" + host + "/user/googleUserInfo.php"
        var getCategory = "https://" + host + "/user/getCategory.php"
        var getProductByType = "https://" + host + "/user/getProductByType.php"
        var getProductByCategory = "https://" + host + "/user/getProductByCategory.php"
        var getSeemoreProduct = "https://" + host + "/user/getSeemoreProduct.php"
        var detailProduct = "https://" + host + "/user/detailProduct.php"
        var saveCart = "https://" + host + "/user/saveCart.php"
        var getCart = "https://" + host + "/user/getCart.php"
        var removeCart = "https://" + host + "/user/removeCart.php"
        var removeAllCart = "https://" + host + "/user/removeAllCart.php"
        var updateCart = "https://" + host + "/user/updateCart.php"
        var getUserInfo = "https://" + host + "/user/getUserInfo.php"
        var getSocialUserInfo = "https://" + host + "/user/getSocialUserInfo.php"
        var updateOnlyPassword = "https://" + host + "/user/updateOnlyPassword.php"
        var updateUserInfo = "https://" + host + "/user/updateUserInfo.php"
        var updateUserInfo2 = "https://" + host + "/user/updateUserInfo2.php"
        var updateUserInfo3 = "https://" + host + "/user/updateUserInfo3.php"
        var updateUserInfo4 = "https://" + host + "/user/updateUserInfo4.php"
        var getUserId = "https://" + host + "/user/getUserId.php"
        var getUserId2 = "https://" + host + "/user/getUserId2.php"
        var updateSecurityQuestion = "https://" + host + "/user/updateSecurityQuestion.php"
        var saveOrder = "https://" + host + "/user/saveOrder.php"
        var saveDetailOrder = "https://" + host + "/user/saveDetailOrder.php"
        var getStateToggleCart = "https://" + host + "/user/getStateToggleCart.php"
        var saveFavourite = "https://" + host + "/user/saveFavourite.php"
        var getFavourite = "https://" + host + "/user/getFavourite.php"
        var removeFavourite = "https://" + host + "/user/removeFavourite.php"
        var getStateToggleFav = "https://" + host + "/user/getStateToggleFav.php"
        var removeAllFav = "https://" + host + "/user/removeAllFav.php"
        var getOrder = "https://" + host + "/user/getOrder.php"
        var removeOrder = "https://" + host + "/user/removeOrder.php"
        var cancelOrder = "https://" + host + "/user/cancelOrder.php"
        var removeAllHistory = "https://" + host + "/user/removeAllHistory.php"
        var getDetailOrder = "https://" + host + "/user/getDetailOrder.php"
        var getSecurityQuestion = "https://" + host + "/user/getSecurityQuestion.php"
        var resetPassword = "https://" + host + "/user/resetPassword.php"
        var getIdOrder = "https://" + host + "/user/getIdOrder.php"
        var getEmailAddress = "https://" + host + "/user/getEmailAddress.php"
        var checkRegister = "https://" + host + "/user/checkRegister.php"
        var filterProduct = "https://" + host + "/user/filterProduct.php"
        var searchProduct = "https://" + host + "/user/searchProduct.php"
        var searchResult = "https://" + host + "/user/searchResult.php"
    }
}